eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    
---    
spring:
  profiles: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service.streamline/eureka
      
---
spring:
  profiles: docker-compose
                
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka
